(scroll-bar-mode -1)
(tool-bar-mode -1)
(blink-cursor-mode 0)
(setq inhibit-startup-screen t)
(setq inhibit-startup-message t)
(setq ring-bell-function 'ignore)
(setq package-enable-at-startup nil)
(setq-default frame-title-format '(""))
(setq-default initial-scratch-message nil)
